baseURL: https://sympt.io/
languageCode: en-us
title: Welcome to Sympt.io
theme: q-tracker
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
defaultContentLanguage: en
# defaultContentLanguageInSubdir: true
languages:
  en:
    params:
    weight: 1
  sk:
    title: Vitaj na Sympt.io
    params:
      hero:
        title: Starostlivosť kdekoľvek
        subtitle: Predstavujeme **Quarantinu**, tvoju osobnú Zdravotnú Asistentku, ktorá ti pomôže monitorovať, zaznamenať a reagovať na vlastný zdravotný stav na základe relevantných informácií spojených s COVID-19.
        motivation0: Potrvá menej než 40 sekúnd tvojho času aktualizovať svoj denný zdravotný stav!
        motivation1: Sympt.io ti umožní reportovať akékoľvek príznaky spojené s COVID, ktoré budeš pociťovať. Zozbierané dáta sú bezpečne zdieľané s vybranými vedcami, doktormi a špecialistami pre verejné zdravie, ktorí aktívne pracujú na zastavení šírenia COVID-19.
        seeHow: Pozri sa na to, ako je zasiahnutá COVID-19 tvoja oblasť!
      navbar:
        - title: Domov
          url: /sk
        - title: Info
          url: /sk/#info
        - title: Tím
          url: /sk/#team
        - title: Kontakt
          url: /sk/#contact
      
      section2:
        title: Kľúčové funkcie
        subtitle: 
        features:
        - title: 
          text: Zaznamenaj ako sa cítiš, aby si pomohol šíreniu COVID-19!
          # Icon (from /images/features/___.svg)
          icon: virus
        - title: SLEDOVANIE
          text: 
          icon: docs
        - title: ZMAPUJ SVOJE SYMPTÓMY
          text: 
          icon: keep-distance
        - title: DENNÉ AKTUALIZÁCIE
          text: 
          icon: mask

      sectionMedia:
        title: V médiách
        winners: Víťazi hackathonu Hack the Crisis - Slovakia…
        winningTeamDescription: Odhodlaný tím 10 entuziastických riešiteľov, analystov, zdravotníckych profesionálov, vedcov, vývojárov a dizajnérov prináša prvú slovenskú aplikáciu na sledovanie symptómov COVID-19.
        media:
        - name: ".týždeň"
          quote: Slováci hackovali koronakrízu. Navrhli, ako si uľahčiť život v izolácii aj ako pomôcť nemocniciam.
          # job: Accountant
          img: images/logos/tyzden-black.svg
          url: https://www.tyzden.sk/spolocnost/63820/slovaci-hackovali-koronakrizu-navrhli-ako-si-ulahcit-zivot-v-izolacii-aj-ako-pomoct-nemocniciam/
        - name: "RTVS"
          quote:  Die App und der zweitbeste Vorschlag Namens „Q-Tracker" können auch an dem internationalen Unterstützungsprojekt teilnehmen
          img: images/logos/rtvs.svg
          url: https://dersi.rtvs.sk/clanky/nachrichten/221797/virtuelles-projekt-hack-the-crisis-slovakia
        - name: "HN online"
          quote: Najväčší hackathon v dejinách Slovenska priniesol digitálne nápady do boja s COVID-19
          img: images/logos/hnonline.png
          url: https://style.hnonline.sk/tech/2126568-hack-the-crisis-najvacsi-hackathon-v-dejinach-slovenska-priniesol-digitalne-napady-do-boja-s-covid-19
        - name: "PC revue"
          # job: Seesame, s.r.o.
          quote: Uspeli nápady na odbremenenie zdravotníkov, predvídanie nakazených aj ľahší život v izolácii
          img: images/logos/pcrevue.png
          url: https://www.pcrevue.sk/a/Uspeli-napady-na-odbremenenie-zdravotnikov--predvidanie-nakazenych

      sectionTeam:
        title: Kto tvorí Sympt.io
        members:
        - name: JAKUB KMEC
          image: illustrations/faces/jakub.png
          title: ML RESEARCHER AT UCL
        - name: PETER KOVACS
          image: illustrations/faces/peter.png
          title: CONSULTANT
        - name: TOMAS BEL
          image: illustrations/faces/tomas.png
          title: Entrepreneur
        - name: PRITI RANKA
          image: illustrations/faces/priti.png
          title: UX DESIGNER
        - name: RAUNAK SACHDEVA
          image: illustrations/faces/raunak.png
          title: UI DESIGNER
        - name: DOMINIK SIVÁK
          image: illustrations/faces/dominik.png
          title: FULL STACK DEVELOPER
        - name: ADRIANA FURDOVÁ
          image: illustrations/faces/adriana.png
          title: MEDICAL DOCTOR
        - name: JÁN MARGETA
          image: illustrations/faces/jan.png
          title: MEDICAL IMAGING SCIENTIST

      footer:
        company: SPOLOČNOSŤ
        aboutUs: O nás
        team: Tím
        contact: Kontakt
        features: Vlastnosti
        howItWorks: Ako to funguje
        pricing: Cenník
        legal: PRÁVO
        privacy: Súkromie
        terms: Podmienky
        security: Ochrana
        invest:

      sectionContactForm:
        contactUs: Kontaktujte nás
        name: Meno
        nameHint: Napíšte svoje meno
        email: E-mail
        emailHint: Vložte svoj email
        message: Správa
        messageHint: Text správy
        submit: Odoslať
params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: Your COVID 19 symptom tracker
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/logo4.svg
    link: /
  font:
    name: "Roboto"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Self Care Anywhere
    # Hero subtitle (optional)
    subtitle: Introducing **Quarantina**, your personal Healthcare Assistant, who helps you monitor, track and improve your health with actionable health information related to COVID 19.
    # image: illustrations/symptio.png
    selfAssessmentText: Self Assessment test
    motivation0: Takes less than 40 seconds of your time to update your daily health condition!
    motivation1: Q-Tracker lets you self-report any COVID related health symptoms you experience. Aggregate data is securely shared with select scientists, doctors and public health professionals who are actively working to stop the spread of COVID-19. 
    seeHow: See how COVID 19 is affected in your area!
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    #- systek
    #- tribe
    #- kromo
    #- infinite
    #- gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
   - title: Home
     url: /
   - title: Info
     url: /#info
   - title: Team
     url: /#team
   - title: Contact
     url: /#contact
  #  - title: SK
  #    url: /sk
  #- title: Dropdown
  #  sublinks:
  #  - title: Dropdown item
  #    url: /
  #  - title: Dropdown item
  #    url: /
  #  - title: Dropdown item
  #    url: /
  #- title: Log in
  #  url: /
  #- title: Sign up
  #  url: /
  #  button: true
  #section1:
  #  title: Great power comes
  #  subtitle: with great responsibility
  #  tiles:
  #  - title: App builder
  #    icon: mouse-globe
  #    text: This is some explanatory text that is on two rows
  #    url: /
  #    buttonText: Free trial
  #  - title: Cloud integration
  #    icon: laptop-cloud
  #    text: This is some explanatory text that is on two rows
  #    url: /
  #    buttonText: Get started
  #  - title: Add-ons & plugins
  #    icon: plug-cloud
  #    text: This is some explanatory text that is on two rows
  #    url: /
  #    buttonText: Get started
  section2:
   title: Key features
   subtitle: 
   features:
   - title: 
     text: Self-report how you feel to help stop the spread of COVID-19!
     # Icon (from /images/features/___.svg)
     icon: virus
   - title: TRACKING
     text: 
     icon: docs
   - title: MAPPING YOUR SYMPTOMS
     text: 
     icon: keep-distance
   - title: DAILY UPDATES
     text: 
     icon: mask
#  section3:
#    title: One platform
#    subtitle: To rule them all
#    image: illustrations/mockups/app-mockup.png
#    buttonText: Get started
#    buttonLink: "#"
  sectionMedia:
    title: In the media
    winners: Winners of Hack the Crisis - Slovakia. 
    winningTeamDescription: A dedicated team of 10 enthusiastic problem solvers, analysts, healthcare professionals, data scientists, developers and designers bring to you Slovakia’s first COVID symptom tracker
    media:
    - name: ".týždeň"
      quote: Slováci hackovali koronakrízu. Navrhli, ako si uľahčiť život v izolácii aj ako pomôcť nemocniciam.
      # job: Accountant
      img: images/logos/tyzden-black.svg
      url: https://www.tyzden.sk/spolocnost/63820/slovaci-hackovali-koronakrizu-navrhli-ako-si-ulahcit-zivot-v-izolacii-aj-ako-pomoct-nemocniciam/
    - name: "RTVS"
      quote:  Die App und der zweitbeste Vorschlag Namens „Q-Tracker" können auch an dem internationalen Unterstützungsprojekt teilnehmen
      img: images/logos/rtvs.svg
      url: https://dersi.rtvs.sk/clanky/nachrichten/221797/virtuelles-projekt-hack-the-crisis-slovakia
    - name: "HN online"
      quote: Najväčší hackathon v dejinách Slovenska priniesol digitálne nápady do boja s COVID-19
      img: images/logos/hnonline.png
      url: https://style.hnonline.sk/tech/2126568-hack-the-crisis-najvacsi-hackathon-v-dejinach-slovenska-priniesol-digitalne-napady-do-boja-s-covid-19
    - name: "PC revue"
      # job: Seesame, s.r.o.
      quote: Uspeli nápady na odbremenenie zdravotníkov, predvídanie nakazených aj ľahší život v izolácii
      img: images/logos/pcrevue.png
      url: https://www.pcrevue.sk/a/Uspeli-napady-na-odbremenenie-zdravotnikov--predvidanie-nakazenych
  sectionTeam:
   title: Behind Sympt.io
   members:
   - name: JAKUB KMEC
     image: illustrations/faces/jakub.png
     title: ML RESEARCHER AT UCL
   - name: PETER KOVACS
     image: illustrations/faces/peter.png
     title: CONSULTANT
   - name: TOMAS BEL
     image: illustrations/faces/tomas.png
     title: Entrepreneur
   - name: PRITI RANKA
     image: illustrations/faces/priti.png
     title: UX DESIGNER
   - name: RAUNAK SACHDEVA
     image: illustrations/faces/raunak.png
     title: UI DESIGNER
   - name: DOMINIK SIVÁK
     image: illustrations/faces/dominik.png
     title: FULL STACK DEVELOPER
   - name: ADRIANA FURDOVÁ
     image: illustrations/faces/adriana.png
     title: MEDICAL DOCTOR
   - name: JÁN MARGETA
     image: illustrations/faces/jan.png
     title: MEDICAL IMAGING SCIENTIST

  #  image: illustrations/team.png
  #  subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
   #clients:
   #- name: .Týždeň
   #  quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat $
   #  job: Accountant
   #  img: 1
  section5: true
  sectionContactForm:
    contactUs: Contact us
    name: Name
    nameHint: Enter your name
    email: E-mail
    emailHint: Enter your email
    message: Message
    messageHint: Write us a message
    submit: Submit
  footer:
    company: COMPANY
    aboutUs: About us
    team: Team
    contact: Contact
    features: Features
    howItWorks: How it works
    pricing: Pricing
    legal: LEGAL
    privacy: Privacy
    terms: Terms
    security: Security
    invest:
  
    # Logo (from /images/logos/___)
    logo: default-monochrome.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    # - link: https://github.com/crisis-hackers
    #   # Icons are from Font Awesome
    #   icon: github
    #- link: https://github.com/crisis-hackers
    #  icon: dribbble
    - link: https://www.facebook.com/sympt.io/
      icon: facebook
    - link: https://twitter.com/symptio
      icon: twitter
    - link: https://www.instagram.com/sympt.io/
      icon: instagram
    - link: https://www.linkedin.com/company/symptio
      icon: linkedin
    #- link: https://bitbucket.org/#
    #  icon: bitbucket
    #bulmalogo: false
    #quicklinks:
    #  column1:
    #    title: "Product"
    #    links:
    #    - text: Discover features
    #      link: /
    #    - text: Why choose our product?
    #      link: /
    #    - text: Compare features
    #      link: /
    #    - text: Our roadmap
    #      link: /
    #    - text: AGB
    #      link: /agb
    #  column2:
    #    title: "Docs"
    #    links:
    #    - text: Get started
    #      link: /
    #    - text: User guides
    #      link: /
    #    - text: Admin guide
    #      link: /
    #    - text: Developers
    #      link: /
    #  column3:
    #    title: "Blog"
    #    links:
    #    - text: Latest news
    #      link: /blog/first
    #    - text: Tech articles
    #      link: /blog/second
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
