baseURL: https://q-tracker.kardio.me/
languageCode: en-us
title: Welcome to Q-Tracker
theme: q-tracker
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/logo4.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Self Care Anywhere
    # Hero subtitle (optional)
    subtitle: Introducing **Quarantina**, your personal Healthcare Assistant, who helps you monitor, track and improve your health with actionable health information related to COVID 19.
    # Button text
    buttontext: Get it on Google Play
    # Where the main hero button links to
    buttonlink: "https://play.google.com/"
    # Hero image (from static/images/___)
    image: illustrations/dark.png
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    #- systek
    #- tribe
    #- kromo
    #- infinite
    #- gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
   - title: Home
     url: /
   - title: Info
     url: /
   - title: Team
     url: /
   - title: Contact
     url: /
  #- title: Dropdown
  #  sublinks:
  #  - title: Dropdown item
  #    url: /
  #  - title: Dropdown item
  #    url: /
  #  - title: Dropdown item
  #    url: /
  #- title: Log in
  #  url: /
  #- title: Sign up
  #  url: /
  #  button: true
  #section1:
  #  title: Great power comes
  #  subtitle: with great responsibility
  #  tiles:
  #  - title: App builder
  #    icon: mouse-globe
  #    text: This is some explanatory text that is on two rows
  #    url: /
  #    buttonText: Free trial
  #  - title: Cloud integration
  #    icon: laptop-cloud
  #    text: This is some explanatory text that is on two rows
  #    url: /
  #    buttonText: Get started
  #  - title: Add-ons & plugins
  #    icon: plug-cloud
  #    text: This is some explanatory text that is on two rows
  #    url: /
  #    buttonText: Get started
  section2:
   title: Key features
   subtitle: 
   features:
   - title: 
     text: Self-report how you feel to help stop the spread of COVID-19!
     # Icon (from /images/illustrations/icons/___.svg)
     icon: laptop-globe
   - title: TRACKING
     text: 
     icon: doc-sync
   - title: MAPPING YOUR SYMPTOMS
     text: 
     icon: mobile-feed
   - title: DAILY UPDATES
     text: 
     icon: mobile-feed
#  section3:
#    title: One platform
#    subtitle: To rule them all
#    image: illustrations/mockups/app-mockup.png
#    buttonText: Get started
#    buttonLink: "#"
  sectionMedia:
    title: In the media
    media:
    - name: ".Týždeň"
      quote: Slováci hackovali koronakrízu. Navrhli, ako si uľahčiť život v izolácii aj ako pomôcť nemocniciam.
      # job: Accountant
      img: 1
    - name: "RTVS"
      quote:  Die App und der zweitbeste Vorschlag Namens „Q-Tracker" können auch an dem internationalen Unterstützungsprojekt teilnehmen, wo sie einen Investor für die Entwicklung des Prototyps finden können.
      img: 2
    - name: "HN online"
      quote: Najväčší hackathon v dejinách Slovenska priniesol digitálne nápady do boja s COVID-19
      img: 3
    - name: "PC revue"
      quote: Uspeli nápady na odbremenenie zdravotníkov, predvídanie nakazených aj ľahší život v izolácii
      img: 4
  section4:
   title: In the media
  #  subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
   clients:
   - name: .Týždeň
     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
     job: Accountant
     img: 1
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: default-monochrome.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/crisis-hackers
      # Icons are from Font Awesome
      icon: github
    #- link: https://github.com/crisis-hackers
    #  icon: dribbble
    #- link: https://facebook.com/#
    #  icon: facebook
    - link: https://twitter.com/q_tracker
      icon: twitter
    #- link: https://bitbucket.org/#
    #  icon: bitbucket
    #bulmalogo: false
    #quicklinks:
    #  column1:
    #    title: "Product"
    #    links:
    #    - text: Discover features
    #      link: /
    #    - text: Why choose our product?
    #      link: /
    #    - text: Compare features
    #      link: /
    #    - text: Our roadmap
    #      link: /
    #    - text: AGB
    #      link: /agb
    #  column2:
    #    title: "Docs"
    #    links:
    #    - text: Get started
    #      link: /
    #    - text: User guides
    #      link: /
    #    - text: Admin guide
    #      link: /
    #    - text: Developers
    #      link: /
    #  column3:
    #    title: "Blog"
    #    links:
    #    - text: Latest news
    #      link: /blog/first
    #    - text: Tech articles
    #      link: /blog/second
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false